// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFiAwY10ZN7M8jVPS9tl_3dJ1LOVA7XKg',
    appId: '1:867104632010:web:b387c61da0fc7c5c775833',
    messagingSenderId: '867104632010',
    projectId: 'project-dequeue',
    authDomain: 'project-dequeue.firebaseapp.com',
    databaseURL: 'https://project-dequeue-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-dequeue.appspot.com',
    measurementId: 'G-VH9MH8DLNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUezQvmFosONmNcXC4LT6Dtf1X_YXwWxY',
    appId: '1:867104632010:android:a1c23ad030dcb451775833',
    messagingSenderId: '867104632010',
    projectId: 'project-dequeue',
    databaseURL: 'https://project-dequeue-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-dequeue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI2P3b4UCkw65VCGauY-j435hnrHJXaIQ',
    appId: '1:867104632010:ios:87c8506a77ef2e2a775833',
    messagingSenderId: '867104632010',
    projectId: 'project-dequeue',
    databaseURL: 'https://project-dequeue-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-dequeue.appspot.com',
    iosClientId: '867104632010-qkae4g2h85fn9tfm16p03por9o0gf3md.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
